"""
Data contracts for process variables, control commands, and physical truth diagnostics.
"""

from dataclasses import dataclass, field
from typing import Optional


@dataclass(slots=True)
class ProcessVariables:
    """
    Sensor-equivalent telemetry exposed by the physical plant to the controller and telemetry bus.
    The controller has access ONLY to these values, not to internal truth states.
    """
    timestamp: float = 0.0                      # Virtual simulation time (s)
    pressure_hyd: float = 1.01325e5             # Hydraulic line pressure (Pa)
    spindle_speed_res: float = 0.0              # Spindle speed from resolver (rad/s)
    pump_speed_res: float = 0.0                 # Pump speed from resolver (rad/s)
    iq_current: float = 0.0                     # Spindle motor quadrature current (A)
    spindle_torque_est: float = 0.0             # Spindle torque derived from Iq (N*m)
    rod_displacement: float = 0.0               # Rod position from transducer (m)
    rod_velocity_est: float = 0.0               # Estimated rod velocity (m/s)
    wob_soft_sensor: float = 0.0                # Estimated Weight-On-Bit / axial force (N)

    @property
    def pressure_bar(self) -> float:
        """Hydraulic pressure in bar."""
        return self.pressure_hyd / 1.0e5

    @property
    def spindle_rpm(self) -> float:
        """Spindle speed in RPM."""
        return self.spindle_speed_res * 30.0 / 3.141592653589793

    @property
    def pump_rpm(self) -> float:
        """Pump speed in RPM."""
        return self.pump_speed_res * 30.0 / 3.141592653589793


@dataclass(slots=True)
class ControlCommands:
    """
    Actuator commands generated by the controller and latched via Zero-Order Hold.
    """
    timestamp: float = 0.0                      # Virtual simulation time (s)
    pump_speed_cmd_rpm: float = 0.0             # Commanded pump speed (RPM)
    spindle_speed_cmd_rpm: float = 0.0          # Commanded spindle speed (RPM)
    enable_pump: bool = True                    # Pump drive enable flag
    enable_spindle: bool = True                 # Spindle drive enable flag

    @property
    def pump_speed_cmd_rads(self) -> float:
        """Commanded pump speed in rad/s."""
        return self.pump_speed_cmd_rpm * 3.141592653589793 / 30.0

    @property
    def spindle_speed_cmd_rads(self) -> float:
        """Commanded spindle speed in rad/s."""
        return self.spindle_speed_cmd_rpm * 3.141592653589793 / 30.0


@dataclass(slots=True)
class TruthDiagnostics:
    """
    Physical truth states for validation, logging, and UI 3D visualization.
    The controller must NEVER inspect these fields.
    """
    timestamp: float = 0.0
    rod_position_true: float = 0.0              # True rod axial displacement (m)
    rod_velocity_true: float = 0.0              # True rod velocity (m/s)
    rod_acceleration_true: float = 0.0          # True rod acceleration (m/s^2)
    chamber_pressure_true: float = 1.01325e5    # True hydraulic chamber pressure (Pa)
    pump_flow_rate: float = 0.0                 # Forward pump discharge flow (m^3/s)
    bypass_flow_rate: float = 0.0               # Calibrated orifice bypass flow (m^3/s)
    leakage_flow_rate: float = 0.0              # Piston seal leakage flow (m^3/s)
    seal_friction_force: float = 0.0            # Dynamic seal friction (N)
    axial_cutting_force_true: float = 0.0       # True normal reaction force / WOB (N)
    spindle_cutting_torque_true: float = 0.0    # True instantaneous cutting torque (N*m)
    penetration_depth: float = 0.0              # Tool penetration into Inconel 718 sphere (m)
    contact_area: float = 0.0                   # Instantaneous tool-workpiece contact area (m^2)
    material_removal_rate: float = 0.0          # Volumetric MRR (m^3/s)
    cumulative_volume_removed: float = 0.0      # Total removed material volume (m^3)
    spindle_speed_true: float = 0.0             # True spindle mechanical speed (rad/s)
    pump_speed_true: float = 0.0                # True pump mechanical speed (rad/s)
    chip_thickness: float = 0.0                 # Instantaneous uncut chip thickness (m)
    total_disturbance_f: float = 0.0            # True physical lump disturbance (N/s^2 or Pa/s)
    leso_disturbance_est: float = 0.0           # LESO estimated disturbance z_3
    operating_mode: str = "INITIALIZING"        # Supervisory state machine name
